"""
DBC2C Converter Template
========================
Copy this file and modify the convert() function to implement your code generator.

canvas_data structure:
{
    "version": 2,
    "dbc_file": "path/to/file.dbc" | null,
    "messages": [
        {
            "name": "MessageName",
            "frame_id": 123,
            "frame_id_hex": "0x7B",
            "length": 8,
            "senders": ["ECU1"],
            "signals": [
                {
                    "name": "SignalName",
                    "start_bit": 0,
                    "length": 8,
                    "byte_order": "big_endian",
                    "factor": 1.0,
                    "offset": 0.0,
                    "minimum": 0.0,
                    "maximum": 255.0,
                    "unit": "rpm",
                    "choices": {"0": "Off", "1": "On"},
                    "comment": "Signal description",
                    "canvas": {
                        "id": "abc123",
                        "node": "ECU1",
                        "direction": "tx",
                        "x": 100.0,
                        "y": 200.0,
                        "condition": { ... } | null
                    }
                }
            ]
        }
    ],
    "custom_nodes": [
        {
            "type": "custom",
            "id": "def456",
            "signal": "RadarSpeedMap",
            "target_variable": "radar_speed",
            "description": "Maps DBC speed to radar",
            "source_message": "VehicleStatus",
            "source_signal": "VehicleSpeed",
            "mapping_table": [
                {"dbc_value": "0", "radar_value": "OFF"},
                {"dbc_value": "1", "radar_value": "ON"}
            ],
            "x": 500.0,
            "y": 300.0
        }
    ],
    "links": [
        {
            "id": "link123",
            "source_id": "abc123",
            "target_id": "def456",
            "label": "data flow"
        }
    ]
}
"""

from pathlib import Path


def convert(canvas_data: dict, output_dir: str) -> None:
    """
    Convert canvas data to code.

    Args:
        canvas_data: Complete canvas data structure (see docstring above)
        output_dir: User-selected output directory

    Raises:
        Exception: On conversion failure
    """
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    # Generate header file
    _generate_header(output, canvas_data)

    # Generate source files for each message
    for message in canvas_data.get("messages", []):
        _generate_message_source(output, message)

    # Generate custom node files
    for node in canvas_data.get("custom_nodes", []):
        _generate_custom_node_source(output, node)


def _generate_header(output: Path, canvas_data: dict) -> None:
    """Generate a common header file."""
    lines = [
        "/* Auto-generated by DBC2C Converter */",
        "#ifndef DBC2C_generated_H",
        "#define DBC2C_generated_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    # Generate message structs
    for message in canvas_data.get("messages", []):
        msg_name = message["name"]
        lines.append(f"/* Message: {msg_name} (ID: 0x{message['frame_id']:X}) */")
        lines.append(f"typedef struct {{")
        for signal in message.get("signals", []):
            sig_name = signal["name"]
            sig_len = signal.get("length", 8)
            c_type = _signal_c_type(sig_len)
            comment = signal.get("comment", "")
            if comment:
                lines.append(f"    {c_type} {sig_name}; /* {comment} */")
            else:
                lines.append(f"    {c_type} {sig_name};")
        lines.append(f"}} {msg_name}_t;")
        lines.append("")

    # Generate custom node function declarations
    for node in canvas_data.get("custom_nodes", []):
        func_name = node["signal"].replace(" ", "_")
        lines.append(f"/* Custom node: {node['signal']} */")
        lines.append(f"void {func_name}_convert(uint8_t raw_value, void* output);")
        lines.append("")

    lines.append("#endif /* DBC2C_generated_H */")

    (output / "dbc2c_generated.h").write_text("\n".join(lines), encoding="utf-8")


def _generate_message_source(output: Path, message: dict) -> None:
    """Generate source file for a message."""
    msg_name = message["name"]
    lines = [
        f"/* Auto-generated: {msg_name} */",
        f'#include "dbc2c_generated.h"',
        "",
    ]

    for signal in message.get("signals", []):
        sig_name = signal["name"]
        choices = signal.get("choices")

        lines.append(f"/* Signal: {sig_name} */")
        if choices:
            lines.append(f"/* Choices: {choices} */")
        lines.append(f"void {msg_name}_{sig_name}_decode(uint8_t* data, {sig_name}_t* output) {{")
        lines.append(f"    /* TODO: Implement signal decoding */")
        lines.append(f"}}")
        lines.append("")

    (output / f"{msg_name}.c").write_text("\n".join(lines), encoding="utf-8")


def _generate_custom_node_source(output: Path, node: dict) -> None:
    """Generate source file for a custom node."""
    node_name = node["signal"]
    func_name = node_name.replace(" ", "_")
    mapping_table = node.get("mapping_table", [])

    lines = [
        f"/* Auto-generated: {node_name} */",
        f'#include "dbc2c_generated.h"',
        "",
        f"/* {node.get('description', '')} */",
    ]

    if mapping_table:
        lines.append(f"/* Mapping table:")
        for m in mapping_table:
            lines.append(f" *   {m['dbc_value']} -> {m['radar_value']}")
        lines.append(f" */")
        lines.append("")

    lines.append(f"void {func_name}_convert(uint8_t raw_value, void* output) {{")
    lines.append(f"    /* TODO: Implement mapping conversion */")
    lines.append(f"    switch (raw_value) {{")
    for m in mapping_table:
        dbc_val = m["dbc_value"]
        radar_val = m["radar_value"]
        try:
            int_val = int(dbc_val)
            lines.append(f"        case {int_val}: /* {radar_val} */")
        except ValueError:
            lines.append(f"        case 0x{dbc_val}: /* {radar_val} */")
        lines.append(f"            /* TODO: set output to {radar_val} */")
        lines.append(f"            break;")
    lines.append(f"        default:")
    lines.append(f"            /* Unknown value */")
    lines.append(f"            break;")
    lines.append(f"    }}")
    lines.append(f"}}")

    (output / f"{func_name}.c").write_text("\n".join(lines), encoding="utf-8")


def _signal_c_type(bit_length: int) -> str:
    """Return appropriate C type for signal bit length."""
    if bit_length <= 8:
        return "uint8_t"
    elif bit_length <= 16:
        return "uint16_t"
    elif bit_length <= 32:
        return "uint32_t"
    else:
        return "uint64_t"
